export const COUNTRY_CODE = Object.freeze({
  ISL: "ISL", // アイスランド
  IRL: "IRL", // アイルランド
  AZE: "AZE", // アゼルバイジャン
  AFG: "AFG", // アフガニスタン
  USA: "USA", // アメリカ合衆国
  VIR: "VIR", // アメリカ領ヴァージン諸島
  ASM: "ASM", // アメリカ領サモア
  ARE: "ARE", // アラブ首長国連邦
  DZA: "DZA", // アルジェリア
  ARG: "ARG", // アルゼンチン
  ABW: "ABW", // アルバ
  ALB: "ALB", // アルバニア
  ARM: "ARM", // アルメニア
  AIA: "AIA", // アンギラ
  AGO: "AGO", // アンゴラ
  ATG: "ATG", // アンティグア・バーブーダ
  AND: "AND", // アンドラ
  YEM: "YEM", // イエメン
  GBR: "GBR", // イギリス
  IOT: "IOT", // イギリス領インド洋地域
  VGB: "VGB", // イギリス領ヴァージン諸島
  ISR: "ISR", // イスラエル
  ITA: "ITA", // イタリア
  IRQ: "IRQ", // イラク
  IRN: "IRN", // イラン・イスラム共和国
  IND: "IND", // インド
  IDN: "IDN", // インドネシア
  WLF: "WLF", // ウォリス・フツナ
  UGA: "UGA", // ウガンダ
  UKR: "UKR", // ウクライナ
  UZB: "UZB", // ウズベキスタン
  URY: "URY", // ウルグアイ
  ECU: "ECU", // エクアドル
  EGY: "EGY", // エジプト
  EST: "EST", // エストニア
  SWZ: "SWZ", // エスワティニ
  ETH: "ETH", // エチオピア
  ERI: "ERI", // エリトリア
  SLV: "SLV", // エルサルバドル
  AUS: "AUS", // オーストラリア
  AUT: "AUT", // オーストリア
  ALA: "ALA", // オーランド諸島
  OMN: "OMN", // オマーン
  NLD: "NLD", // オランダ
  GHA: "GHA", // ガーナ
  CPV: "CPV", // カーボベルデ
  GGY: "GGY", // ガーンジー
  GUY: "GUY", // ガイアナ
  KAZ: "KAZ", // カザフスタン
  QAT: "QAT", // カタール
  UMI: "UMI", // 合衆国領有小離島
  CAN: "CAN", // カナダ
  GAB: "GAB", // ガボン
  CMR: "CMR", // カメルーン
  GMB: "GMB", // ガンビア
  KHM: "KHM", // カンボジア
  MKD: "MKD", // 北マケドニア
  MNP: "MNP", // 北マリアナ諸島
  GIN: "GIN", // ギニア
  GNB: "GNB", // ギニアビサウ
  CYP: "CYP", // キプロス
  CUB: "CUB", // キューバ
  CUW: "CUW", // キュラソー
  GRC: "GRC", // ギリシャ
  KIR: "KIR", // キリバス
  KGZ: "KGZ", // キルギス
  GTM: "GTM", // グアテマラ
  GLP: "GLP", // グアドループ
  GUM: "GUM", // グアム
  KWT: "KWT", // クウェート
  COK: "COK", // クック諸島
  GRL: "GRL", // グリーンランド
  CXR: "CXR", // クリスマス島
  GRD: "GRD", // グレナダ
  HRV: "HRV", // クロアチア
  CYM: "CYM", // ケイマン諸島
  KEN: "KEN", // ケニア
  CIV: "CIV", // コートジボワール
  CCK: "CCK", // ココス（キーリング）諸島
  CRI: "CRI", // コスタリカ
  COM: "COM", // コモロ
  COL: "COL", // コロンビア
  COG: "COG", // コンゴ共和国
  COD: "COD", // コンゴ民主共和国
  SAU: "SAU", // サウジアラビア
  SGS: "SGS", // サウスジョージア・サウスサンドウィッチ諸島
  WSM: "WSM", // サモア
  STP: "STP", // サントメ・プリンシペ
  BLM: "BLM", // サン・バルテルミー
  ZMB: "ZMB", // ザンビア
  SPM: "SPM", // サンピエール島・ミクロン島
  SMR: "SMR", // サンマリノ
  MAF: "MAF", // サン・マルタン（フランス領）
  SLE: "SLE", // シエラレオネ
  DJI: "DJI", // ジブチ
  GIB: "GIB", // ジブラルタル
  JEY: "JEY", // ジャージー
  JAM: "JAM", // ジャマイカ
  GEO: "GEO", // ジョージア
  SYR: "SYR", // シリア・アラブ共和国
  SGP: "SGP", // シンガポール
  SXM: "SXM", // シント・マールテン（オランダ領）
  ZWE: "ZWE", // ジンバブエ
  CHE: "CHE", // スイス
  SWE: "SWE", // スウェーデン
  SDN: "SDN", // スーダン
  SJM: "SJM", // スヴァールバル諸島およびヤンマイエン島
  ESP: "ESP", // スペイン
  SUR: "SUR", // スリナム
  LKA: "LKA", // スリランカ
  SVK: "SVK", // スロバキア
  SVN: "SVN", // スロベニア
  SYC: "SYC", // セーシェル
  GNQ: "GNQ", // 赤道ギニア
  SEN: "SEN", // セネガル
  SRB: "SRB", // セルビア
  KNA: "KNA", // セントクリストファー・ネイビス
  VCT: "VCT", // セントビンセント・グレナディーン
  SHN: "SHN", // セントヘレナ・アセンションおよびトリスタンダクーニャ
  LCA: "LCA", // セントルシア
  SOM: "SOM", // ソマリア
  SLB: "SLB", // ソロモン諸島
  TCA: "TCA", // タークス・カイコス諸島
  THA: "THA", // タイ
  KOR: "KOR", // 大韓民国
  TWN: "TWN", // 台湾（中華民国）
  TJK: "TJK", // タジキスタン
  TZA: "TZA", // タンザニア
  CZE: "CZE", // チェコ
  TCD: "TCD", // チャド
  CAF: "CAF", // 中央アフリカ共和国
  CHN: "CHN", // 中華人民共和国
  TUN: "TUN", // チュニジア
  PRK: "PRK", // 朝鮮民主主義人民共和国
  CHL: "CHL", // チリ
  TUV: "TUV", // ツバル
  DNK: "DNK", // デンマーク
  DEU: "DEU", // ドイツ
  TGO: "TGO", // トーゴ
  TKL: "TKL", // トケラウ
  DOM: "DOM", // ドミニカ共和国
  DMA: "DMA", // ドミニカ国
  TTO: "TTO", // トリニダード・トバゴ
  TKM: "TKM", // トルクメニスタン
  TUR: "TUR", // トルコ
  TON: "TON", // トンガ
  NGA: "NGA", // ナイジェリア
  NRU: "NRU", // ナウル
  NAM: "NAM", // ナミビア
  ATA: "ATA", // 南極
  NIU: "NIU", // ニウエ
  NIC: "NIC", // ニカラグア
  NER: "NER", // ニジェール
  JPN: "JPN", // 日本
  ESH: "ESH", // 西サハラ
  NCL: "NCL", // ニューカレドニア
  NZL: "NZL", // ニュージーランド
  NPL: "NPL", // ネパール
  NFK: "NFK", // ノーフォーク島
  NOR: "NOR", // ノルウェー
  HMD: "HMD", // ハード島とマクドナルド諸島
  BHR: "BHR", // バーレーン
  HTI: "HTI", // ハイチ
  PAK: "PAK", // パキスタン
  VAT: "VAT", // バチカン市国
  PAN: "PAN", // パナマ
  VUT: "VUT", // バヌアツ
  BHS: "BHS", // バハマ
  PNG: "PNG", // パプアニューギニア
  BMU: "BMU", // バミューダ
  PLW: "PLW", // パラオ
  PRY: "PRY", // パラグアイ
  BRB: "BRB", // バルバドス
  PSE: "PSE", // パレスチナ
  HUN: "HUN", // ハンガリー
  BGD: "BGD", // バングラデシュ
  TLS: "TLS", // 東ティモール
  PCN: "PCN", // ピトケアン
  FJI: "FJI", // フィジー
  PHL: "PHL", // フィリピン
  FIN: "FIN", // フィンランド
  BTN: "BTN", // ブータン
  BVT: "BVT", // ブーベ島
  PRI: "PRI", // プエルトリコ
  FRO: "FRO", // フェロー諸島
  FLK: "FLK", // フォークランド（マルビナス）諸島
  BRA: "BRA", // ブラジル
  FRA: "FRA", // フランス
  GUF: "GUF", // フランス領ギアナ
  PYF: "PYF", // フランス領ポリネシア
  ATF: "ATF", // フランス領南方・南極地域
  BGR: "BGR", // ブルガリア
  BFA: "BFA", // ブルキナファソ
  BRN: "BRN", // ブルネイ・ダルサラーム
  BDI: "BDI", // ブルンジ
  VNM: "VNM", // ベトナム
  BEN: "BEN", // ベナン
  VEN: "VEN", // ベネズエラ・ボリバル共和国
  BLR: "BLR", // ベラルーシ
  BLZ: "BLZ", // ベリーズ
  PER: "PER", // ペルー
  BEL: "BEL", // ベルギー
  POL: "POL", // ポーランド
  BIH: "BIH", // ボスニア・ヘルツェゴビナ
  BWA: "BWA", // ボツワナ
  BES: "BES", // ボネール、シント・ユースタティウスおよびサバ
  BOL: "BOL", // ボリビア多民族国
  PRT: "PRT", // ポルトガル
  HKG: "HKG", // 香港
  HND: "HND", // ホンジュラス
  MHL: "MHL", // マーシャル諸島
  MAC: "MAC", // マカオ
  MDG: "MDG", // マダガスカル
  MYT: "MYT", // マヨット
  MWI: "MWI", // マラウイ
  MLI: "MLI", // マリ
  MLT: "MLT", // マルタ
  MTQ: "MTQ", // マルティニーク
  MYS: "MYS", // マレーシア
  IMN: "IMN", // マン島
  FSM: "FSM", // ミクロネシア連邦
  ZAF: "ZAF", // 南アフリカ
  SSD: "SSD", // 南スーダン
  MMR: "MMR", // ミャンマー
  MEX: "MEX", // メキシコ
  MUS: "MUS", // モーリシャス
  MRT: "MRT", // モーリタニア
  MOZ: "MOZ", // モザンビーク
  MCO: "MCO", // モナコ
  MDV: "MDV", // モルディブ
  MDA: "MDA", // モルドバ共和国
  MAR: "MAR", // モロッコ
  MNG: "MNG", // モンゴル
  MNE: "MNE", // モンテネグロ
  MSR: "MSR", // モントセラト
  JOR: "JOR", // ヨルダン
  LAO: "LAO", // ラオス人民民主共和国
  LVA: "LVA", // ラトビア
  LTU: "LTU", // リトアニア
  LBY: "LBY", // リビア
  LIE: "LIE", // リヒテンシュタイン
  LBR: "LBR", // リベリア
  ROU: "ROU", // ルーマニア
  LUX: "LUX", // ルクセンブルク
  RWA: "RWA", // ルワンダ
  LSO: "LSO", // レソト
  LBN: "LBN", // レバノン
  REU: "REU", // レユニオン
  RUS: "RUS", // ロシア連邦
})
