-- データベースユーザーを作成
CREATE USER "${POSTGRES_USER}" WITH PASSWORD '${POSTGRES_PASSWORD}';

-- データベースを作成し、オーナーを設定
CREATE DATABASE "${POSTGRES_DB}" OWNER "${POSTGRES_USER}";

-- 必要に応じて権限を付与
GRANT ALL PRIVILEGES ON DATABASE "${POSTGRES_DB}" TO "${POSTGRES_USER}";
