"""add_description_to_recipe

Revision ID: 205468106972
Revises: 7e2e575e60d9
Create Date: 2024-11-22 11:20:39.305617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '205468106972'
down_revision = '7e2e575e60d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
