services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${CERTS_PATH}:/etc/nginx/certs:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - app_network

  app:
    image: python:3.13-slim
    container_name: app
    build:
      dockerfile: docker/app/Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ../data:/data
    environment:
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - APP_PORT=${APP_PORT}
      - FLASK_ENV=${FLASK_ENV}
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:16
    container_name: db
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker/db/docker-entrypoint-initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
