name: Deploy Client

on:
  push:
    branches:
      - main
    paths:
      - 'client/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies and build
        working-directory: client
        run: |
          npm ci
          npm run build

      - name: Check AWS CLI version
        run: aws --version

      # S3 にアップロード
      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync ./dist s3://clientstaticsitestack-oishininjaclientstaticsitebu-vsjfcawiwtwu --delete
